version: "3.4"

services:
    exercisetrackermern:
        image: exercisetrackermern
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
    backend:
        image: backend
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 5000:5000
